---
# ansible/roles/frontend/tasks/main.yml
- name: Create application directory
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: Copy frontend application
  copy:
    src: /tmp/setup/
    dest: "{{ app_dir }}"
    owner: ubuntu
    group: ubuntu
    mode: 0755
    remote_src: yes

- name: Install npm dependencies
  npm:
    path: "{{ app_dir }}"
    state: present
  become: yes
  become_user: ubuntu

- name: Build React application
  shell: |
    cd {{ app_dir }} && npm run build
  become: yes
  become_user: ubuntu
  environment:
    NODE_ENV: "{{ env }}"

- name: Configure Nginx
  template:
    src: nginx-site.conf.j2
    dest: "{{ nginx_conf_dir }}/mern-app"
    owner: root
    group: root
    mode: 0644

- name: Enable Nginx site
  file:
    src: "{{ nginx_conf_dir }}/mern-app"
    dest: /etc/nginx/sites-enabled/mern-app
    state: link

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Create environment file
  template:
    src: env.j2
    dest: "{{ app_dir }}/.env.{{ env }}"
    owner: ubuntu
    group: ubuntu
    mode: 0600

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
    enabled: yes