name: Terraform Infrastructure Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_db_master_password: ${{ secrets.DB_MASTER_PASSWORD }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/environments

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Get Environment
      id: environment
      run: |
        echo "env_name=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT

    - name: Terraform Init
      run: |
        cd ${{ steps.environment.outputs.env_name }}
        terraform init

    - name: Terraform Format
      run: |
        cd ${{ steps.environment.outputs.env_name }}
        terraform fmt -check

    - name: Terraform Validate
      run: |
        cd ${{ steps.environment.outputs.env_name }}
        terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: |
        cd ${{ steps.environment.outputs.env_name }}
        terraform plan -no-color

    - name: Terraform Apply
      run: |
        cd ${{ steps.environment.outputs.env_name }}
        terraform apply -auto-approve